# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRSt1MUBB_v42zFdz8LI-xb3vYBJWHDi
"""

"""
Data Provenance Script: NHANES 2017-2018
This script demonstrates how the original XPT files were fetched directly from the CDC servers
before being zipped into 'NHANES_Dataset_2017.zip' for the E-GACT repository.
"""

import os
import urllib.request

def download_nhanes_data():
    base_url = "https://wwwn.cdc.gov/Nchs/Nhanes/2017-2018/"

    # List of required XPT files for the E-GACT pipeline
    files = [
        "DEMO_J.XPT",  # Demographics
        "BMX_J.XPT",   # Body Measures
        "BPQ_J.XPT",   # Blood Pressure
        "MCQ_J.XPT",   # Medical Conditions
        "GHB_J.XPT",   # Glycohemoglobin
        "GLU_J.XPT"    # Fasting Glucose
    ]

    output_dir = "Raw_CDC_NHANES"
    os.makedirs(output_dir, exist_ok=True)

    print("Downloading raw NHANES 2017-2018 files from official CDC servers...")

    for file in files:
        url = base_url + file
        output_path = os.path.join(output_dir, file)

        try:
            print(f"Fetching {file}...")
            urllib.request.urlretrieve(url, output_path)
            print(f"  -> Successfully saved to {output_path}")
        except Exception as e:
            print(f"  -> Failed to download {file}. Error: {e}")

if __name__ == "__main__":
    download_nhanes_data()
    print("\nDownload complete. To create the repository mirror, these files were compressed into 'NHANES_Dataset_2017.zip'.")